version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitFeature123Project
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestGitFeature123Project
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testgitfeature123.integrations:e11
  packages:
  - name: TestGitFeature123Project
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.1081
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.1.0.0.1081
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1081
